### ISSUE TITLE
No integration with navigation options

### ISSUE THREAD

**Issue by jozo-krstanovic** [perezpz/burger-menu#23]
Doesn't support the use of react-router-dom or I haven't found a way to connect them.
No documentation to explain how it would work with navigation of any type even though the package specifies it is used for navigation (which hamburger menus often are).
The biggest issue is documentation as there is no way to know how to correctly use the package nor can it be found anywhere on the internet as far as I've looked. So applying CSS styles seems impossible, routing through the use of menu items seems impossible. In fact, adding any type of functionality to the menu items seems impossible.

**Comment by perezpz** [comment]
Please check the example.

**Comment by jozo-krstanovic** [comment]
Example was checked. It is compatible with HTML native href elements for navigation.
Possible future feature could be enabling the use of react-router-dom elements (such as <Link> and UseNavigate()).
